name: edconnect_admin
description: "EdConnect Admin is a Flutter-based application designed to streamline administrative tasks for educational institutions. It provides a user-friendly interface for managing student records, scheduling, and communication between staff and students"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  # Firebase Dependencies
  firebase_core: ^3.13.0
  firebase_dart: ^1.3.4
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.6
  cloud_functions: ^5.4.0
  firebase_messaging: ^15.2.5


  # Html Dependencies
  html_editor_enhanced: ^2.6.0
  pointer_interceptor: ^0.10.1+2
  desktop_drop: ^0.5.0
  # Other Dependencies
  image_cropper: ^9.1.0
  share_plus: ^10.1.4
  pdf: ^3.11.3
  file_picker: ^8.3.7
  pointycastle: ^3.9.1
  flex_color_picker: ^3.7.0
  printing: ^5.14.2

  intl: ^0.19.0
  http: ^1.3.0
  web:
  crypto: ^3.0.6
  video_player: ^2.9.5
  chewie: ^1.11.1
  just_audio: ^0.9.46
  csv:
  excel:
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3 
  connectivity_plus: ^6.1.3
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
 
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/placeholder_dark_mode_template_en.png
      - assets/placeholder_light_mode_template_en.png
      - assets/edconnect_logo.png
      - assets/edconnect_system_logo.png
      - assets/edconnect_logo_transparent.png
      - assets/PIP_Dark_Mode_Work_In_Progress_Animated.gif
      - assets/pip_branding_dark_mode_horizontalxxxhdpi.png
      - assets/pip_branding_light_mode_horizontalxxxhdpi.png
      - assets/pip_branding_light_mode_verticalxxxhdpi.png
      - assets/pip_branding_dark_mode_verticalxxxhdpi.png
      - assets/fonts/PIPCustomIcons.ttf
      - assets/PIP_Logo_Loading_Light_Mode_Animated.gif


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PIPCustomIcons 
      fonts:
        - asset: assets/fonts/PIPCustomIcons.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# Flutter Splash Screen
# Run flutter pub run flutter_native_splash:create after changing splash screen
flutter_native_splash:
  color: "#192b4c"
  image: assets/edconnect_logo_transparent.png
  branding: assets/pip_branding_dark_mode_horizontalxxxhdpi.png
  android: false
  ios: false
  fullscreen: true

# This part adds the flutter launcher icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/light_mode_template_en.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/light_mode_template_en.png"
    background_color: "#ffffff"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "assets/light_mode_template_en.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "assets/light_mode_template_en.png"

